### ISSUE TITLE
Rename posts with date or create drafts folder within content

### ISSUE THREAD

**Issue by alicetragedy** [cloudfleet/blog#3]
As the list of blog posts grows, it would be great to either see them chronologically in the `content` folder or to have a dedicated `drafts` folder for the posts that need proofreading, as I think it would be more efficient than scanning for titles I recognise ;) 
@metakermit do you have any idea if renaming the files (including published ones) will have an effect on the slugs/break something? Do you have any preferred solution — renaming vs. drafts folder?

I'm game with either, I'd just like to sort it out soon before we start to have a lot of content. Would love to hear your thoughts!

**Comment by metakermit** [comment]
Yeah, that's a good suggestion. I think we can rename the files, yes (maybe
year_month_day_title) and probably a drafts folder will work too. We should
test it locally probably just to make sure it all works.

**Comment by easye** [comment]
If we rename the blog content files, will the URIs they have been served
under until this point still work?

Tersely pecked on a Nexus 5

**Comment by metakermit** [comment]
That's what we have to test.

**Comment by alicetragedy** [comment]
I will take a look at this later and test it locally to see if renaming the files is possible.

**Comment by DoubleMalt** [comment]
The urls will not change if the property "slug" is set in the metadata. Should be set in all blog posts so far.

**Comment by alicetragedy** [comment]
done via 4be147a5e846c815dd8359ec3180c50efaa607a7 — I think we can close this issue. Thanks @metakermit! :tada:

**Comment by metakermit** [comment]
Np, thanks for opening & closing the issue – I'm a bit lost in the
ever-growing TODO list, so didn't even spot this one came from GitHub.
Luckily there's reply-by-mail feature :)

**Comment by alicetragedy** [comment]
yep! I spend too much time on GitHub 😶but love the link above that takes you directly to your open issues and PRs, it's like a geeky to-do list. \o/
