### ISSUE TITLE
Add/fix atom/rss feed

### ISSUE THREAD

**Issue by alicetragedy** [cloudfleet/blog#4]
Do we have an RSS or atom feed — and if we don't, should we maybe add that?
We've gotten a question regarding this via twitter, checking the page I see that there's a 'setup' for it, but the link is just `cloudfleet.io/blog`. 
Would be awesome to add this, as I think it might get us some recurrent traffic. 
I'm happy to look into this if needed.

**Comment by easye** [comment]
I tweeted that we were looking into this https://twitter.com/ineluctablymod/status/675664351097962496.  
Is this something @metakermit knows about?

**Comment by metakermit** [comment]
Fixed and replied to original reporter on Twitter.
